= AdamantiaMUD Core

This repository contains the core libraries for the Adamantia MUD engine.

== Prior Work

(or "On the shoulders of giants")

Adamantia began its life as a TypeScript fork of the https://github.com/RanvierMUD/ranviermud/[RanvierMUD] engine for Node.js. It has been stripped to the core and rebuilt with inspiration from other MUD engines like CircleMUD as well as games like Dungeons & Dragons.

== Contributing

Anyone willing to contribute is welcome to https://github.com/AdamantiaMUD/core/issues/new[open an issue]. Code contributions are always welcome! For ideas, check out the https://github.com/AdamantiaMUD/core/issues[issue tracker] and/or project road map (coming soon).

This project welcomes any and all who wish to contribute. To aid in this, we have adopted the https://www.contributor-covenant.org/[Contributor Covenant]. You can read link:./CONDUCT.adoc[the full text] of the code here.

== License

AdamantiaMUD is released as open source under the MIT license. See the link:./LICENSE.adoc[license] file for the full text of the license.
